nameservers:
  # IPv4
  - "223.5.5.5" # 阿里 DNS
  - "223.6.6.6" # 阿里 DNS
  - "114.114.114.114" # 114DNS
  - "114.114.115.115" # 114DNS
  - "119.29.29.29" # 腾讯 DNSPod DNS
  - "180.76.76.76" # 百度 DNS
  - "8.8.8.8" # Google DNS
  - "8.8.4.4" # Google DNS
  - "94.140.14.14" # AdGuard DNS
  - "1.1.1.1" # Cloudflare DNS
  # - "127.0.0.1" # 本机 DNS

  # IPv6
  - "2400:3200::1" # 阿里 DNS
  - "2400:3200:baba::1" # 阿里 DNS
  - "2402:4e00::" # 腾讯 DNSPod DNS
  - "2a10:50c0::ad1:ff" # CleanBrowsing DNS
  - "2001:4860:4860::8888" # Google DNS
  - "2001:4860:4860::8844" # Google DNS
  - "2606:4700:4700::1111" # Cloudflare DNS

  # 加密 DNS
  - "https://dns.alidns.com/dns-query" # 阿里 DoH
  - "tls://dns.alidns.com" # 阿里 DoT
  - "https://doh.pub/dns-query" # 腾讯 DNSPod DoH
  - "https://1.12.12.12/dns-query" # 腾讯 DNSPod DoH(IP)
  - "https://120.53.53.53/dns-query" # 腾讯 DNSPod DoH(IP)
  - "https://sm2.doh.pub/dns-query" # 腾讯 DNSPod DoH(国密)
  - "tls://dot.pub" # 腾讯 DNSPod DoT
  - "tls://1.12.12.12" # 腾讯 DNSPod DoT(IP)
  - "tls://120.53.53.53" # 腾讯 DNSPod DoT(IP)
  # - "https://dns.cloudflare.com/dns-query" # Cloudflare DoH 无法连通
  - "tls://1dot1dot1dot1.cloudflare-dns.com" # Cloudflare DoT
  # - "https://dns.google/dns-query" # Google DoH 无法连通
  - "tls://dns.google" # Google DoT
  - "tls://dns.adguard-dns.com" # AdGuard DoT
  # - "quic://dns.adguard-dns.com" # AdGuard DoQ

# 测试域名
domains:
  - baidu.com
  - google.com
  - store.steampowered.com
  - store.epicgames.com
  - github.com
  - bing.com
  - www.rockstargames.com
  - chat.openai.com
  - platform.openai.com
  - dash.cloudflare.com
  - wikipedia.org
  - wikiwand.org
  - www.google-analytics.com
  - hm.baidu.com
  - api.segment.io
  - a.quora.com
  - munchkin.marketo.net
  - js-agent.newrelic.com
  - static.doubleclick.net
  - js.hs-scripts.com
  - adservice.google.com
  - tracking.g2crowd.com
  - adservice.google.com
